version: '2'

services:
  nginx:
    image: nginx
    container_name: histovec-nginx
    volumes:
 #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/share/nginx/html
    ports:
      - ${PORT}:80
    restart: always

